// api/product/v1/product.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/product/v1/product.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`
	MinPrice      int32                  `protobuf:"varint,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      int32                  `protobuf:"varint,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	InStock       bool                   `protobuf:"varint,7,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	SortBy        string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // "price", "rating", "newest"
	SortOrder     string                 `protobuf:"bytes,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // "asc", "desc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListProductsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListProductsRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListProductsRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListProductsRequest) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchProductsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{3}
}

func (x *ListProductsReply) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ProductInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Basic info
	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Brand       string `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Pricing
	ActualPrice  string `protobuf:"bytes,5,opt,name=actual_price,json=actualPrice,proto3" json:"actual_price,omitempty"`
	SellingPrice string `protobuf:"bytes,6,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	Discount     string `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	PriceNumeric int32  `protobuf:"varint,8,opt,name=price_numeric,json=priceNumeric,proto3" json:"price_numeric,omitempty"`
	// Categorization
	Category    string `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory string `protobuf:"bytes,10,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	// Stock & Seller
	OutOfStock bool   `protobuf:"varint,11,opt,name=out_of_stock,json=outOfStock,proto3" json:"out_of_stock,omitempty"`
	Seller     string `protobuf:"bytes,12,opt,name=seller,proto3" json:"seller,omitempty"`
	// Ratings
	AverageRating string  `protobuf:"bytes,13,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	RatingNumeric float32 `protobuf:"fixed32,14,opt,name=rating_numeric,json=ratingNumeric,proto3" json:"rating_numeric,omitempty"`
	// Media
	Images       []string `protobuf:"bytes,15,rep,name=images,proto3" json:"images,omitempty"`
	PrimaryImage string   `protobuf:"bytes,16,opt,name=primary_image,json=primaryImage,proto3" json:"primary_image,omitempty"`
	// Product details
	ProductDetails map[string]string `protobuf:"bytes,17,rep,name=product_details,json=productDetails,proto3" json:"product_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// URLs
	Url string `protobuf:"bytes,18,opt,name=url,proto3" json:"url,omitempty"`
	Pid string `protobuf:"bytes,19,opt,name=pid,proto3" json:"pid,omitempty"`
	// Metadata
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Engagement
	ViewCount     int32 `protobuf:"varint,22,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	ClickCount    int32 `protobuf:"varint,23,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_api_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *ProductInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductInfo) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ProductInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductInfo) GetActualPrice() string {
	if x != nil {
		return x.ActualPrice
	}
	return ""
}

func (x *ProductInfo) GetSellingPrice() string {
	if x != nil {
		return x.SellingPrice
	}
	return ""
}

func (x *ProductInfo) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *ProductInfo) GetPriceNumeric() int32 {
	if x != nil {
		return x.PriceNumeric
	}
	return 0
}

func (x *ProductInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductInfo) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *ProductInfo) GetOutOfStock() bool {
	if x != nil {
		return x.OutOfStock
	}
	return false
}

func (x *ProductInfo) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *ProductInfo) GetAverageRating() string {
	if x != nil {
		return x.AverageRating
	}
	return ""
}

func (x *ProductInfo) GetRatingNumeric() float32 {
	if x != nil {
		return x.RatingNumeric
	}
	return 0
}

func (x *ProductInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductInfo) GetPrimaryImage() string {
	if x != nil {
		return x.PrimaryImage
	}
	return ""
}

func (x *ProductInfo) GetProductDetails() map[string]string {
	if x != nil {
		return x.ProductDetails
	}
	return nil
}

func (x *ProductInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProductInfo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *ProductInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProductInfo) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ProductInfo) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

var File_api_product_v1_product_proto protoreflect.FileDescriptor

const file_api_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1capi/product/v1/product.proto\x12\x0eapi.product.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x85\x02\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x05R\bmaxPrice\x12\x19\n" +
	"\bin_stock\x18\a \x01(\bR\ainStock\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\tR\tsortOrder\"_\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\x93\x01\n" +
	"\x11ListProductsReply\x127\n" +
	"\bproducts\x18\x01 \x03(\v2\x1b.api.product.v1.ProductInfoR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xef\x06\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\factual_price\x18\x05 \x01(\tR\vactualPrice\x12#\n" +
	"\rselling_price\x18\x06 \x01(\tR\fsellingPrice\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\tR\bdiscount\x12#\n" +
	"\rprice_numeric\x18\b \x01(\x05R\fpriceNumeric\x12\x1a\n" +
	"\bcategory\x18\t \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\n" +
	" \x01(\tR\vsubCategory\x12 \n" +
	"\fout_of_stock\x18\v \x01(\bR\n" +
	"outOfStock\x12\x16\n" +
	"\x06seller\x18\f \x01(\tR\x06seller\x12%\n" +
	"\x0eaverage_rating\x18\r \x01(\tR\raverageRating\x12%\n" +
	"\x0erating_numeric\x18\x0e \x01(\x02R\rratingNumeric\x12\x16\n" +
	"\x06images\x18\x0f \x03(\tR\x06images\x12#\n" +
	"\rprimary_image\x18\x10 \x01(\tR\fprimaryImage\x12X\n" +
	"\x0fproduct_details\x18\x11 \x03(\v2/.api.product.v1.ProductInfo.ProductDetailsEntryR\x0eproductDetails\x12\x10\n" +
	"\x03url\x18\x12 \x01(\tR\x03url\x12\x10\n" +
	"\x03pid\x18\x13 \x01(\tR\x03pid\x129\n" +
	"\n" +
	"created_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\x16 \x01(\x05R\tviewCount\x12\x1f\n" +
	"\vclick_count\x18\x17 \x01(\x05R\n" +
	"clickCount\x1aA\n" +
	"\x13ProductDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd9\x02\n" +
	"\aProduct\x12g\n" +
	"\n" +
	"GetProduct\x12!.api.product.v1.GetProductRequest\x1a\x1b.api.product.v1.ProductInfo\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/products/{id}\x12l\n" +
	"\fListProducts\x12#.api.product.v1.ListProductsRequest\x1a!.api.product.v1.ListProductsReply\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/products\x12w\n" +
	"\x0eSearchProducts\x12%.api.product.v1.SearchProductsRequest\x1a!.api.product.v1.ListProductsReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/products/searchB3\n" +
	"\x0eapi.product.v1P\x01Z\x1fyinni_backend/api/product/v1;v1b\x06proto3"

var (
	file_api_product_v1_product_proto_rawDescOnce sync.Once
	file_api_product_v1_product_proto_rawDescData []byte
)

func file_api_product_v1_product_proto_rawDescGZIP() []byte {
	file_api_product_v1_product_proto_rawDescOnce.Do(func() {
		file_api_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)))
	})
	return file_api_product_v1_product_proto_rawDescData
}

var file_api_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_product_v1_product_proto_goTypes = []any{
	(*GetProductRequest)(nil),     // 0: api.product.v1.GetProductRequest
	(*ListProductsRequest)(nil),   // 1: api.product.v1.ListProductsRequest
	(*SearchProductsRequest)(nil), // 2: api.product.v1.SearchProductsRequest
	(*ListProductsReply)(nil),     // 3: api.product.v1.ListProductsReply
	(*ProductInfo)(nil),           // 4: api.product.v1.ProductInfo
	nil,                           // 5: api.product.v1.ProductInfo.ProductDetailsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_product_v1_product_proto_depIdxs = []int32{
	4, // 0: api.product.v1.ListProductsReply.products:type_name -> api.product.v1.ProductInfo
	5, // 1: api.product.v1.ProductInfo.product_details:type_name -> api.product.v1.ProductInfo.ProductDetailsEntry
	6, // 2: api.product.v1.ProductInfo.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: api.product.v1.ProductInfo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: api.product.v1.Product.GetProduct:input_type -> api.product.v1.GetProductRequest
	1, // 5: api.product.v1.Product.ListProducts:input_type -> api.product.v1.ListProductsRequest
	2, // 6: api.product.v1.Product.SearchProducts:input_type -> api.product.v1.SearchProductsRequest
	4, // 7: api.product.v1.Product.GetProduct:output_type -> api.product.v1.ProductInfo
	3, // 8: api.product.v1.Product.ListProducts:output_type -> api.product.v1.ListProductsReply
	3, // 9: api.product.v1.Product.SearchProducts:output_type -> api.product.v1.ListProductsReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_product_v1_product_proto_init() }
func file_api_product_v1_product_proto_init() {
	if File_api_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_v1_product_proto_rawDesc), len(file_api_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_v1_product_proto_goTypes,
		DependencyIndexes: file_api_product_v1_product_proto_depIdxs,
		MessageInfos:      file_api_product_v1_product_proto_msgTypes,
	}.Build()
	File_api_product_v1_product_proto = out.File
	file_api_product_v1_product_proto_goTypes = nil
	file_api_product_v1_product_proto_depIdxs = nil
}
