// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/product/v1/product.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductGetProduct = "/api.product.v1.Product/GetProduct"
const OperationProductListProducts = "/api.product.v1.Product/ListProducts"
const OperationProductSearchProducts = "/api.product.v1.Product/SearchProducts"

type ProductHTTPServer interface {
	// GetProduct Get product by ID
	GetProduct(context.Context, *GetProductRequest) (*ProductInfo, error)
	// ListProducts List products
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	// SearchProducts Search products
	SearchProducts(context.Context, *SearchProductsRequest) (*ListProductsReply, error)
}

func RegisterProductHTTPServer(s *http.Server, srv ProductHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/products/{id}", _Product_GetProduct0_HTTP_Handler(srv))
	r.GET("/v1/products", _Product_ListProducts0_HTTP_Handler(srv))
	r.GET("/v1/products/search", _Product_SearchProducts0_HTTP_Handler(srv))
}

func _Product_GetProduct0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProductInfo)
		return ctx.Result(200, reply)
	}
}

func _Product_ListProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Product_SearchProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductSearchProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchProducts(ctx, req.(*SearchProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

type ProductHTTPClient interface {
	// GetProduct Get product by ID
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *ProductInfo, err error)
	// ListProducts List products
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	// SearchProducts Search products
	SearchProducts(ctx context.Context, req *SearchProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
}

type ProductHTTPClientImpl struct {
	cc *http.Client
}

func NewProductHTTPClient(client *http.Client) ProductHTTPClient {
	return &ProductHTTPClientImpl{client}
}

// GetProduct Get product by ID
func (c *ProductHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*ProductInfo, error) {
	var out ProductInfo
	pattern := "/v1/products/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProducts List products
func (c *ProductHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchProducts Search products
func (c *ProductHTTPClientImpl) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductSearchProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
