// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/product/v1/product.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductCancelEmbeddingGeneration = "/api.product.v1.Product/CancelEmbeddingGeneration"
const OperationProductGenerateEmbeddings = "/api.product.v1.Product/GenerateEmbeddings"
const OperationProductGetEmbeddingStatus = "/api.product.v1.Product/GetEmbeddingStatus"
const OperationProductGetFeaturedProducts = "/api.product.v1.Product/GetFeaturedProducts"
const OperationProductGetProduct = "/api.product.v1.Product/GetProduct"
const OperationProductGetProductByPID = "/api.product.v1.Product/GetProductByPID"
const OperationProductGetProductSeedJobStatus = "/api.product.v1.Product/GetProductSeedJobStatus"
const OperationProductGetSimilarProducts = "/api.product.v1.Product/GetSimilarProducts"
const OperationProductListProducts = "/api.product.v1.Product/ListProducts"
const OperationProductSearchProducts = "/api.product.v1.Product/SearchProducts"
const OperationProductStartProductSeedJob = "/api.product.v1.Product/StartProductSeedJob"

type ProductHTTPServer interface {
	// CancelEmbeddingGenerationAdmin-only: Cancel embedding generation
	CancelEmbeddingGeneration(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// GenerateEmbeddings Admin-only: Generate embeddings
	GenerateEmbeddings(context.Context, *GenerateEmbeddingsRequest) (*GenerateEmbeddingsResponse, error)
	// GetEmbeddingStatusAdmin-only: Get embedding status
	GetEmbeddingStatus(context.Context, *GetEmbeddingStatusRequest) (*GetEmbeddingStatusResponse, error)
	// GetFeaturedProducts Get featured products
	GetFeaturedProducts(context.Context, *GetFeaturedProductsRequest) (*ListProductsReply, error)
	// GetProduct Get product by ID
	GetProduct(context.Context, *GetProductRequest) (*ProductInfo, error)
	// GetProductByPID Get product by Flipkart PID
	GetProductByPID(context.Context, *GetProductByPIDRequest) (*ProductInfo, error)
	// GetProductSeedJobStatus Admin-only: Get runtime product seeding job status
	GetProductSeedJobStatus(context.Context, *GetProductSeedJobStatusRequest) (*GetProductSeedJobStatusResponse, error)
	// GetSimilarProducts Get similar products
	GetSimilarProducts(context.Context, *GetSimilarProductsRequest) (*ListProductsReply, error)
	// ListProducts List products
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsReply, error)
	// SearchProducts Search products
	SearchProducts(context.Context, *SearchProductsRequest) (*ListProductsReply, error)
	// StartProductSeedJob Admin-only: Start runtime product seeding job
	StartProductSeedJob(context.Context, *StartProductSeedJobRequest) (*StartProductSeedJobResponse, error)
}

func RegisterProductHTTPServer(s *http.Server, srv ProductHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/products/id/{id}", _Product_GetProduct0_HTTP_Handler(srv))
	r.GET("/v1/products/pid/{pid}", _Product_GetProductByPID0_HTTP_Handler(srv))
	r.GET("/v1/products", _Product_ListProducts0_HTTP_Handler(srv))
	r.GET("/v1/products/search", _Product_SearchProducts0_HTTP_Handler(srv))
	r.GET("/v1/products/featured", _Product_GetFeaturedProducts0_HTTP_Handler(srv))
	r.GET("/v1/products/{id}/similar", _Product_GetSimilarProducts0_HTTP_Handler(srv))
	r.POST("/v1/admin/embeddings/generate", _Product_GenerateEmbeddings0_HTTP_Handler(srv))
	r.GET("/v1/admin/embeddings/status", _Product_GetEmbeddingStatus0_HTTP_Handler(srv))
	r.POST("/v1/admin/embeddings/cancel", _Product_CancelEmbeddingGeneration0_HTTP_Handler(srv))
	r.POST("/v1/admin/products/seed", _Product_StartProductSeedJob0_HTTP_Handler(srv))
	r.GET("/v1/admin/products/seed/status", _Product_GetProductSeedJobStatus0_HTTP_Handler(srv))
}

func _Product_GetProduct0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetProduct)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProduct(ctx, req.(*GetProductRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProductInfo)
		return ctx.Result(200, reply)
	}
}

func _Product_GetProductByPID0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductByPIDRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetProductByPID)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProductByPID(ctx, req.(*GetProductByPIDRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProductInfo)
		return ctx.Result(200, reply)
	}
}

func _Product_ListProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductListProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProducts(ctx, req.(*ListProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Product_SearchProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductSearchProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchProducts(ctx, req.(*SearchProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Product_GetFeaturedProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetFeaturedProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetFeaturedProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFeaturedProducts(ctx, req.(*GetFeaturedProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Product_GetSimilarProducts0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSimilarProductsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetSimilarProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSimilarProducts(ctx, req.(*GetSimilarProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProductsReply)
		return ctx.Result(200, reply)
	}
}

func _Product_GenerateEmbeddings0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateEmbeddingsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGenerateEmbeddings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateEmbeddings(ctx, req.(*GenerateEmbeddingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateEmbeddingsResponse)
		return ctx.Result(200, reply)
	}
}

func _Product_GetEmbeddingStatus0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmbeddingStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetEmbeddingStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmbeddingStatus(ctx, req.(*GetEmbeddingStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmbeddingStatusResponse)
		return ctx.Result(200, reply)
	}
}

func _Product_CancelEmbeddingGeneration0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductCancelEmbeddingGeneration)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelEmbeddingGeneration(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _Product_StartProductSeedJob0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartProductSeedJobRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductStartProductSeedJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartProductSeedJob(ctx, req.(*StartProductSeedJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartProductSeedJobResponse)
		return ctx.Result(200, reply)
	}
}

func _Product_GetProductSeedJobStatus0_HTTP_Handler(srv ProductHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProductSeedJobStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductGetProductSeedJobStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProductSeedJobStatus(ctx, req.(*GetProductSeedJobStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetProductSeedJobStatusResponse)
		return ctx.Result(200, reply)
	}
}

type ProductHTTPClient interface {
	// CancelEmbeddingGenerationAdmin-only: Cancel embedding generation
	CancelEmbeddingGeneration(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GenerateEmbeddings Admin-only: Generate embeddings
	GenerateEmbeddings(ctx context.Context, req *GenerateEmbeddingsRequest, opts ...http.CallOption) (rsp *GenerateEmbeddingsResponse, err error)
	// GetEmbeddingStatusAdmin-only: Get embedding status
	GetEmbeddingStatus(ctx context.Context, req *GetEmbeddingStatusRequest, opts ...http.CallOption) (rsp *GetEmbeddingStatusResponse, err error)
	// GetFeaturedProducts Get featured products
	GetFeaturedProducts(ctx context.Context, req *GetFeaturedProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	// GetProduct Get product by ID
	GetProduct(ctx context.Context, req *GetProductRequest, opts ...http.CallOption) (rsp *ProductInfo, err error)
	// GetProductByPID Get product by Flipkart PID
	GetProductByPID(ctx context.Context, req *GetProductByPIDRequest, opts ...http.CallOption) (rsp *ProductInfo, err error)
	// GetProductSeedJobStatus Admin-only: Get runtime product seeding job status
	GetProductSeedJobStatus(ctx context.Context, req *GetProductSeedJobStatusRequest, opts ...http.CallOption) (rsp *GetProductSeedJobStatusResponse, err error)
	// GetSimilarProducts Get similar products
	GetSimilarProducts(ctx context.Context, req *GetSimilarProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	// ListProducts List products
	ListProducts(ctx context.Context, req *ListProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	// SearchProducts Search products
	SearchProducts(ctx context.Context, req *SearchProductsRequest, opts ...http.CallOption) (rsp *ListProductsReply, err error)
	// StartProductSeedJob Admin-only: Start runtime product seeding job
	StartProductSeedJob(ctx context.Context, req *StartProductSeedJobRequest, opts ...http.CallOption) (rsp *StartProductSeedJobResponse, err error)
}

type ProductHTTPClientImpl struct {
	cc *http.Client
}

func NewProductHTTPClient(client *http.Client) ProductHTTPClient {
	return &ProductHTTPClientImpl{client}
}

// CancelEmbeddingGenerationAdmin-only: Cancel embedding generation
func (c *ProductHTTPClientImpl) CancelEmbeddingGeneration(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin/embeddings/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductCancelEmbeddingGeneration))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GenerateEmbeddings Admin-only: Generate embeddings
func (c *ProductHTTPClientImpl) GenerateEmbeddings(ctx context.Context, in *GenerateEmbeddingsRequest, opts ...http.CallOption) (*GenerateEmbeddingsResponse, error) {
	var out GenerateEmbeddingsResponse
	pattern := "/v1/admin/embeddings/generate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductGenerateEmbeddings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEmbeddingStatusAdmin-only: Get embedding status
func (c *ProductHTTPClientImpl) GetEmbeddingStatus(ctx context.Context, in *GetEmbeddingStatusRequest, opts ...http.CallOption) (*GetEmbeddingStatusResponse, error) {
	var out GetEmbeddingStatusResponse
	pattern := "/v1/admin/embeddings/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetEmbeddingStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFeaturedProducts Get featured products
func (c *ProductHTTPClientImpl) GetFeaturedProducts(ctx context.Context, in *GetFeaturedProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products/featured"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetFeaturedProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProduct Get product by ID
func (c *ProductHTTPClientImpl) GetProduct(ctx context.Context, in *GetProductRequest, opts ...http.CallOption) (*ProductInfo, error) {
	var out ProductInfo
	pattern := "/v1/products/id/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetProduct))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProductByPID Get product by Flipkart PID
func (c *ProductHTTPClientImpl) GetProductByPID(ctx context.Context, in *GetProductByPIDRequest, opts ...http.CallOption) (*ProductInfo, error) {
	var out ProductInfo
	pattern := "/v1/products/pid/{pid}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetProductByPID))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetProductSeedJobStatus Admin-only: Get runtime product seeding job status
func (c *ProductHTTPClientImpl) GetProductSeedJobStatus(ctx context.Context, in *GetProductSeedJobStatusRequest, opts ...http.CallOption) (*GetProductSeedJobStatusResponse, error) {
	var out GetProductSeedJobStatusResponse
	pattern := "/v1/admin/products/seed/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetProductSeedJobStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSimilarProducts Get similar products
func (c *ProductHTTPClientImpl) GetSimilarProducts(ctx context.Context, in *GetSimilarProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products/{id}/similar"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductGetSimilarProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListProducts List products
func (c *ProductHTTPClientImpl) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductListProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SearchProducts Search products
func (c *ProductHTTPClientImpl) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...http.CallOption) (*ListProductsReply, error) {
	var out ListProductsReply
	pattern := "/v1/products/search"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationProductSearchProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// StartProductSeedJob Admin-only: Start runtime product seeding job
func (c *ProductHTTPClientImpl) StartProductSeedJob(ctx context.Context, in *StartProductSeedJobRequest, opts ...http.CallOption) (*StartProductSeedJobResponse, error) {
	var out StartProductSeedJobResponse
	pattern := "/v1/admin/products/seed"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductStartProductSeedJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
