// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/classifier/v1/classifier.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_api_classifier_v1_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_classifier_v1_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_api_classifier_v1_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClassifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyReply) Reset() {
	*x = ClassifyReply{}
	mi := &file_api_classifier_v1_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyReply) ProtoMessage() {}

func (x *ClassifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_classifier_v1_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyReply.ProtoReflect.Descriptor instead.
func (*ClassifyReply) Descriptor() ([]byte, []int) {
	return file_api_classifier_v1_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyReply) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClassifyReply) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_api_classifier_v1_classifier_proto protoreflect.FileDescriptor

const file_api_classifier_v1_classifier_proto_rawDesc = "" +
	"\n" +
	"\"api/classifier/v1/classifier.proto\x12\x11api.classifier.v1\"%\n" +
	"\x0fClassifyRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"Y\n" +
	"\rClassifyReply\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value2^\n" +
	"\n" +
	"Classifier\x12P\n" +
	"\bClassify\x12\".api.classifier.v1.ClassifyRequest\x1a .api.classifier.v1.ClassifyReplyB9\n" +
	"\x11api.classifier.v1P\x01Z\"yinni_backend/api/classifier/v1;v1b\x06proto3"

var (
	file_api_classifier_v1_classifier_proto_rawDescOnce sync.Once
	file_api_classifier_v1_classifier_proto_rawDescData []byte
)

func file_api_classifier_v1_classifier_proto_rawDescGZIP() []byte {
	file_api_classifier_v1_classifier_proto_rawDescOnce.Do(func() {
		file_api_classifier_v1_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_classifier_v1_classifier_proto_rawDesc), len(file_api_classifier_v1_classifier_proto_rawDesc)))
	})
	return file_api_classifier_v1_classifier_proto_rawDescData
}

var file_api_classifier_v1_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_classifier_v1_classifier_proto_goTypes = []any{
	(*ClassifyRequest)(nil), // 0: api.classifier.v1.ClassifyRequest
	(*ClassifyReply)(nil),   // 1: api.classifier.v1.ClassifyReply
}
var file_api_classifier_v1_classifier_proto_depIdxs = []int32{
	0, // 0: api.classifier.v1.Classifier.Classify:input_type -> api.classifier.v1.ClassifyRequest
	1, // 1: api.classifier.v1.Classifier.Classify:output_type -> api.classifier.v1.ClassifyReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_classifier_v1_classifier_proto_init() }
func file_api_classifier_v1_classifier_proto_init() {
	if File_api_classifier_v1_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_classifier_v1_classifier_proto_rawDesc), len(file_api_classifier_v1_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_classifier_v1_classifier_proto_goTypes,
		DependencyIndexes: file_api_classifier_v1_classifier_proto_depIdxs,
		MessageInfos:      file_api_classifier_v1_classifier_proto_msgTypes,
	}.Build()
	File_api_classifier_v1_classifier_proto = out.File
	file_api_classifier_v1_classifier_proto_goTypes = nil
	file_api_classifier_v1_classifier_proto_depIdxs = nil
}
