# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/classifier/v1/classifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/classifier/v1/classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"api/classifier/v1/classifier.proto\x12\x11\x61pi.classifier.v1\"\x1f\n\x0f\x43lassifyRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"@\n\rClassifyReply\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05value\x18\x03 \x01(\t2^\n\nClassifier\x12P\n\x08\x43lassify\x12\".api.classifier.v1.ClassifyRequest\x1a .api.classifier.v1.ClassifyReplyB9\n\x11\x61pi.classifier.v1P\x01Z\"yinni_backend/api/classifier/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.classifier.v1.classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021api.classifier.v1P\001Z\"yinni_backend/api/classifier/v1;v1'
  _globals['_CLASSIFYREQUEST']._serialized_start=57
  _globals['_CLASSIFYREQUEST']._serialized_end=88
  _globals['_CLASSIFYREPLY']._serialized_start=90
  _globals['_CLASSIFYREPLY']._serialized_end=154
  _globals['_CLASSIFIER']._serialized_start=156
  _globals['_CLASSIFIER']._serialized_end=250
# @@protoc_insertion_point(module_scope)
