// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/prompt/v1/prompt.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptRequest) Reset() {
	*x = SendPromptRequest{}
	mi := &file_api_prompt_v1_prompt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptRequest) ProtoMessage() {}

func (x *SendPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_prompt_v1_prompt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptRequest.ProtoReflect.Descriptor instead.
func (*SendPromptRequest) Descriptor() ([]byte, []int) {
	return file_api_prompt_v1_prompt_proto_rawDescGZIP(), []int{0}
}

func (x *SendPromptRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SendPromptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPromptReply) Reset() {
	*x = SendPromptReply{}
	mi := &file_api_prompt_v1_prompt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPromptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPromptReply) ProtoMessage() {}

func (x *SendPromptReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_prompt_v1_prompt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPromptReply.ProtoReflect.Descriptor instead.
func (*SendPromptReply) Descriptor() ([]byte, []int) {
	return file_api_prompt_v1_prompt_proto_rawDescGZIP(), []int{1}
}

func (x *SendPromptReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_api_prompt_v1_prompt_proto protoreflect.FileDescriptor

const file_api_prompt_v1_prompt_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/prompt/v1/prompt.proto\x12\rapi.prompt.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x11SendPromptRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\")\n" +
	"\x0fSendPromptReply\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2o\n" +
	"\x06Prompt\x12e\n" +
	"\n" +
	"SendPrompt\x12 .api.prompt.v1.SendPromptRequest\x1a\x1e.api.prompt.v1.SendPromptReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/promptB1\n" +
	"\rapi.prompt.v1P\x01Z\x1eyinni_backend/api/prompt/v1;v1b\x06proto3"

var (
	file_api_prompt_v1_prompt_proto_rawDescOnce sync.Once
	file_api_prompt_v1_prompt_proto_rawDescData []byte
)

func file_api_prompt_v1_prompt_proto_rawDescGZIP() []byte {
	file_api_prompt_v1_prompt_proto_rawDescOnce.Do(func() {
		file_api_prompt_v1_prompt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_prompt_v1_prompt_proto_rawDesc), len(file_api_prompt_v1_prompt_proto_rawDesc)))
	})
	return file_api_prompt_v1_prompt_proto_rawDescData
}

var file_api_prompt_v1_prompt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_prompt_v1_prompt_proto_goTypes = []any{
	(*SendPromptRequest)(nil), // 0: api.prompt.v1.SendPromptRequest
	(*SendPromptReply)(nil),   // 1: api.prompt.v1.SendPromptReply
}
var file_api_prompt_v1_prompt_proto_depIdxs = []int32{
	0, // 0: api.prompt.v1.Prompt.SendPrompt:input_type -> api.prompt.v1.SendPromptRequest
	1, // 1: api.prompt.v1.Prompt.SendPrompt:output_type -> api.prompt.v1.SendPromptReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_prompt_v1_prompt_proto_init() }
func file_api_prompt_v1_prompt_proto_init() {
	if File_api_prompt_v1_prompt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_prompt_v1_prompt_proto_rawDesc), len(file_api_prompt_v1_prompt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_prompt_v1_prompt_proto_goTypes,
		DependencyIndexes: file_api_prompt_v1_prompt_proto_depIdxs,
		MessageInfos:      file_api_prompt_v1_prompt_proto_msgTypes,
	}.Build()
	File_api_prompt_v1_prompt_proto = out.File
	file_api_prompt_v1_prompt_proto_goTypes = nil
	file_api_prompt_v1_prompt_proto_depIdxs = nil
}
