// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: api/prompt/v1/prompt.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPromptSendPrompt = "/api.prompt.v1.Prompt/SendPrompt"

type PromptHTTPServer interface {
	SendPrompt(context.Context, *SendPromptRequest) (*SendPromptReply, error)
}

func RegisterPromptHTTPServer(s *http.Server, srv PromptHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/prompt", _Prompt_SendPrompt0_HTTP_Handler(srv))
}

func _Prompt_SendPrompt0_HTTP_Handler(srv PromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendPromptRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPromptSendPrompt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendPrompt(ctx, req.(*SendPromptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendPromptReply)
		return ctx.Result(200, reply)
	}
}

type PromptHTTPClient interface {
	SendPrompt(ctx context.Context, req *SendPromptRequest, opts ...http.CallOption) (rsp *SendPromptReply, err error)
}

type PromptHTTPClientImpl struct {
	cc *http.Client
}

func NewPromptHTTPClient(client *http.Client) PromptHTTPClient {
	return &PromptHTTPClientImpl{client}
}

func (c *PromptHTTPClientImpl) SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...http.CallOption) (*SendPromptReply, error) {
	var out SendPromptReply
	pattern := "/v1/prompt"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPromptSendPrompt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
