// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/prompt/v1/prompt.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Prompt_SendPrompt_FullMethodName = "/api.prompt.v1.Prompt/SendPrompt"
)

// PromptClient is the client API for Prompt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptClient interface {
	SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*SendPromptReply, error)
}

type promptClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptClient(cc grpc.ClientConnInterface) PromptClient {
	return &promptClient{cc}
}

func (c *promptClient) SendPrompt(ctx context.Context, in *SendPromptRequest, opts ...grpc.CallOption) (*SendPromptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPromptReply)
	err := c.cc.Invoke(ctx, Prompt_SendPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptServer is the server API for Prompt service.
// All implementations must embed UnimplementedPromptServer
// for forward compatibility.
type PromptServer interface {
	SendPrompt(context.Context, *SendPromptRequest) (*SendPromptReply, error)
	mustEmbedUnimplementedPromptServer()
}

// UnimplementedPromptServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptServer struct{}

func (UnimplementedPromptServer) SendPrompt(context.Context, *SendPromptRequest) (*SendPromptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPrompt not implemented")
}
func (UnimplementedPromptServer) mustEmbedUnimplementedPromptServer() {}
func (UnimplementedPromptServer) testEmbeddedByValue()                {}

// UnsafePromptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptServer will
// result in compilation errors.
type UnsafePromptServer interface {
	mustEmbedUnimplementedPromptServer()
}

func RegisterPromptServer(s grpc.ServiceRegistrar, srv PromptServer) {
	// If the following call panics, it indicates UnimplementedPromptServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Prompt_ServiceDesc, srv)
}

func _Prompt_SendPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServer).SendPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Prompt_SendPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServer).SendPrompt(ctx, req.(*SendPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Prompt_ServiceDesc is the grpc.ServiceDesc for Prompt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Prompt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.prompt.v1.Prompt",
	HandlerType: (*PromptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPrompt",
			Handler:    _Prompt_SendPrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/prompt/v1/prompt.proto",
}
