// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"yinni_backend/app/product/internal/biz"
	"yinni_backend/app/product/internal/data"
	"yinni_backend/app/product/internal/server"
	"yinni_backend/app/product/internal/service"
	"yinni_backend/internal/conf"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, embeddings *conf.Embeddings, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(dataData, embeddings, logger)
	productUsecase := biz.NewProductUsecase(productRepo, embeddings, logger)
	productService := service.NewProductService(productUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, productService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, productService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
