version: "3.9"

services:
  # ---------- AUTH SERVICE ----------
  auth-service:
    build:
      context: .
      dockerfile: app/auth/Dockerfile
    ports:
      - "${AUTH_HTTP_PORT}:8000"
      - "${AUTH_GRPC_PORT}:9000"
    volumes:
      - ./app/auth/configs:/data/conf
    environment:
      KRATOS_SERVER_HTTP_ADDR: 0.0.0.0:8000
      KRATOS_SERVER_GRPC_ADDR: 0.0.0.0:9000
      KRATOS_AUTH_JWT_SECRET: ${JWT_SECRET}
      KRATOS_AUTH_JWT_EXPIRE: ${JWT_EXPIRE}
      KRATOS_DATA_DATABASE_SOURCE: ${DB_SOURCE}
      KRATOS_ADMIN_EMAIL: ${ADMIN_EMAIL}
      KRATOS_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KRATOS_ADMIN_NAME: ${ADMIN_NAME}
      KRATOS_ADMIN_ENABLED: "true"
    depends_on:
      mysql:
        condition: service_healthy

    # ---------- USER SERVICE ----------
  # user-service:
  #   build:
  #     context: .
  #     dockerfile: app/user/Dockerfile
  #   ports:
  #     - "${USER_HTTP_PORT}:8001"
  #     - "${USER_GRPC_PORT}:9001"
  #   volumes:
  #     - ./app/user/configs:/data/conf
  #   environment:
  #     KRATOS_SERVER_HTTP_ADDR: 0.0.0.0:8001
  #     KRATOS_SERVER_GRPC_ADDR: 0.0.0.0:9001
  #     KRATOS_DATA_DATABASE_SOURCE: ${DB_SOURCE}
  #     KRATOS_AUTH_JWT_SECRET: ${JWT_SECRET}
  #     KRATOS_AUTH_JWT_EXPIRE: ${JWT_EXPIRE}
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # ---------- PRODUCT SERVICE ----------
  product-service:
    build:
      context: .
      dockerfile: app/product/Dockerfile
    ports:
      - "${PRODUCT_HTTP_PORT}:8002"
      - "${PRODUCT_GRPC_PORT}:9002"
    volumes:
      - ./app/product/product_dataset.json:/app/product_dataset.json
      - ./app/product/configs:/data/conf
    environment:
      KRATOS_SERVER_HTTP_ADDR: 0.0.0.0:8002
      KRATOS_SERVER_GRPC_ADDR: 0.0.0.0:9002
      KRATOS_DATA_DATABASE_SOURCE: ${DB_SOURCE}
      KRATOS_AUTH_JWT_SECRET: ${JWT_SECRET}
      KRATOS_AUTH_JWT_EXPIRE: ${JWT_EXPIRE}
      AI_API_KEY: ${AI_API_KEY}
      AI_CHAT_URL: ${AI_CHAT_URL}
      AI_EMBEDDING_URL: ${AI_EMBEDDING_URL}
      AI_CHAT_MODEL: ${AI_CHAT_MODEL}
      AI_EMBEDDING_MODEL: ${AI_EMBEDDING_MODEL}
    depends_on:
      mysql:
        condition: service_healthy

  # ---------- PROMPT SERVICE ----------
  # prompt-service:
  #   build:
  #     context: .
  #     dockerfile: app/prompt/Dockerfile
  #   ports:
  #     - "${PROMPT_HTTP_PORT}:8003"
  #     - "${PROMPT_GRPC_PORT}:9003"
  #   volumes:
  #     - ./app/prompt/configs:/data/conf
  #   environment:
  #     KRATOS_SERVER_HTTP_ADDR: 0.0.0.0:8003
  #     KRATOS_SERVER_GRPC_ADDR: 0.0.0.0:9003
  #     KRATOS_DATA_DATABASE_SOURCE: ${DB_SOURCE}
  #     KRATOS_AUTH_JWT_SECRET: ${JWT_SECRET}
  #     KRATOS_AUTH_JWT_EXPIRE: ${JWT_EXPIRE}
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # ---------- PAYMENT SERVICE ----------
  # payment-service:
  #   build:
  #     context: .
  #     dockerfile: app/payment/Dockerfile
  #   ports:
  #     - "${PAYMENT_HTTP_PORT}:8004"
  #     - "${PAYMENT_GRPC_PORT}:9004"
  #   volumes:
  #     - ./app/payment/configs:/data/conf
  #   environment:
  #     KRATOS_SERVER_HTTP_ADDR: 0.0.0.0:8004
  #     KRATOS_SERVER_GRPC_ADDR: 0.0.0.0:9004
  #     KRATOS_DATA_DATABASE_SOURCE: ${DB_SOURCE}
  #     KRATOS_AUTH_JWT_SECRET: ${JWT_SECRET}
  #     KRATOS_AUTH_JWT_EXPIRE: ${JWT_EXPIRE}
  #     PAYMENT_PUBLIC_BASE_URL: ${PAYMENT_PUBLIC_BASE_URL}
  #   depends_on:
  #     mysql:
  #       condition: service_healthy

  # ---------- CLASSIFIER SERVICE ----------
  # classifier-service:
  #   build:
  #     context: .
  #     dockerfile: app/classifier/Dockerfile
  #   ports:
  #     - "9005:9005"   # optional: expose only for local debugging
  #   environment:
  #     GRPC_PORT: "9005"
  #   depends_on:
  #     mysql:
  #       condition: service_healthy


  # ---------- MYSQL ----------
  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s  # Add this to give MySQL time to initialize
