server:
  http:
    addr: ${KRATOS_SERVER_HTTP_ADDR:0.0.0.0:8003}
    timeout: 30s
  grpc:
    addr: ${KRATOS_SERVER_GRPC_ADDR:0.0.0.0:9003}
    timeout: 30s

services:
  product_service_endpoint: "product-service:9002"
  payment_service_endpoint: "payment-service:9004"
  classifier_service_endpoint: "classifier-service:9005"
  timeout: "30s"

auth:
  jwt_secret: ${KRATOS_AUTH_JWT_SECRET:no-secret}
  jwt_expire: 3600
data:
  database:
    driver: mysql
    source: ${KRATOS_DATA_DATABASE_SOURCE:root:root@tcp(mysql:3307)/yinni_db?parseTime=true&charset=utf8mb4&loc=Local}