// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"yinni_backend/app/main/internal/biz"
	"yinni_backend/app/main/internal/data"
	"yinni_backend/app/main/internal/server"
	"yinni_backend/app/main/internal/service"
	"yinni_backend/internal/conf"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	mainRepo := data.NewMainRepo(dataData, logger)
	promptUsecase := biz.NewMainUsecase(mainRepo)
	mainService := service.NewMainService(promptUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, mainService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, mainService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
