// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yinni_backend/ent/predicate"
	"yinni_backend/ent/product"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ProductUpdate) SetUpdateTime(v time.Time) *ProductUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *ProductUpdate) SetOriginalID(v string) *ProductUpdate {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableOriginalID(v *string) *ProductUpdate {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProductUpdate) SetTitle(v string) *ProductUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableTitle(v *string) *ProductUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *ProductUpdate) SetBrand(v string) *ProductUpdate {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableBrand(v *string) *ProductUpdate {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProductUpdate) SetDescription(v string) *ProductUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableDescription(v *string) *ProductUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProductUpdate) ClearDescription() *ProductUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetActualPrice sets the "actual_price" field.
func (_u *ProductUpdate) SetActualPrice(v string) *ProductUpdate {
	_u.mutation.SetActualPrice(v)
	return _u
}

// SetNillableActualPrice sets the "actual_price" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableActualPrice(v *string) *ProductUpdate {
	if v != nil {
		_u.SetActualPrice(*v)
	}
	return _u
}

// ClearActualPrice clears the value of the "actual_price" field.
func (_u *ProductUpdate) ClearActualPrice() *ProductUpdate {
	_u.mutation.ClearActualPrice()
	return _u
}

// SetSellingPrice sets the "selling_price" field.
func (_u *ProductUpdate) SetSellingPrice(v string) *ProductUpdate {
	_u.mutation.SetSellingPrice(v)
	return _u
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSellingPrice(v *string) *ProductUpdate {
	if v != nil {
		_u.SetSellingPrice(*v)
	}
	return _u
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (_u *ProductUpdate) ClearSellingPrice() *ProductUpdate {
	_u.mutation.ClearSellingPrice()
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *ProductUpdate) SetDiscount(v string) *ProductUpdate {
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableDiscount(v *string) *ProductUpdate {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *ProductUpdate) ClearDiscount() *ProductUpdate {
	_u.mutation.ClearDiscount()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ProductUpdate) SetCategory(v string) *ProductUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCategory(v *string) *ProductUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSubCategory sets the "sub_category" field.
func (_u *ProductUpdate) SetSubCategory(v string) *ProductUpdate {
	_u.mutation.SetSubCategory(v)
	return _u
}

// SetNillableSubCategory sets the "sub_category" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSubCategory(v *string) *ProductUpdate {
	if v != nil {
		_u.SetSubCategory(*v)
	}
	return _u
}

// SetOutOfStock sets the "out_of_stock" field.
func (_u *ProductUpdate) SetOutOfStock(v bool) *ProductUpdate {
	_u.mutation.SetOutOfStock(v)
	return _u
}

// SetNillableOutOfStock sets the "out_of_stock" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableOutOfStock(v *bool) *ProductUpdate {
	if v != nil {
		_u.SetOutOfStock(*v)
	}
	return _u
}

// SetSeller sets the "seller" field.
func (_u *ProductUpdate) SetSeller(v string) *ProductUpdate {
	_u.mutation.SetSeller(v)
	return _u
}

// SetNillableSeller sets the "seller" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableSeller(v *string) *ProductUpdate {
	if v != nil {
		_u.SetSeller(*v)
	}
	return _u
}

// ClearSeller clears the value of the "seller" field.
func (_u *ProductUpdate) ClearSeller() *ProductUpdate {
	_u.mutation.ClearSeller()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *ProductUpdate) SetAverageRating(v string) *ProductUpdate {
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableAverageRating(v *string) *ProductUpdate {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// ClearAverageRating clears the value of the "average_rating" field.
func (_u *ProductUpdate) ClearAverageRating() *ProductUpdate {
	_u.mutation.ClearAverageRating()
	return _u
}

// SetImages sets the "images" field.
func (_u *ProductUpdate) SetImages(v []string) *ProductUpdate {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *ProductUpdate) AppendImages(v []string) *ProductUpdate {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *ProductUpdate) ClearImages() *ProductUpdate {
	_u.mutation.ClearImages()
	return _u
}

// SetProductDetails sets the "product_details" field.
func (_u *ProductUpdate) SetProductDetails(v []map[string]string) *ProductUpdate {
	_u.mutation.SetProductDetails(v)
	return _u
}

// AppendProductDetails appends value to the "product_details" field.
func (_u *ProductUpdate) AppendProductDetails(v []map[string]string) *ProductUpdate {
	_u.mutation.AppendProductDetails(v)
	return _u
}

// ClearProductDetails clears the value of the "product_details" field.
func (_u *ProductUpdate) ClearProductDetails() *ProductUpdate {
	_u.mutation.ClearProductDetails()
	return _u
}

// SetURL sets the "url" field.
func (_u *ProductUpdate) SetURL(v string) *ProductUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableURL(v *string) *ProductUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *ProductUpdate) ClearURL() *ProductUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetPid sets the "pid" field.
func (_u *ProductUpdate) SetPid(v string) *ProductUpdate {
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *ProductUpdate) SetNillablePid(v *string) *ProductUpdate {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// SetStyleCode sets the "style_code" field.
func (_u *ProductUpdate) SetStyleCode(v string) *ProductUpdate {
	_u.mutation.SetStyleCode(v)
	return _u
}

// SetNillableStyleCode sets the "style_code" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableStyleCode(v *string) *ProductUpdate {
	if v != nil {
		_u.SetStyleCode(*v)
	}
	return _u
}

// ClearStyleCode clears the value of the "style_code" field.
func (_u *ProductUpdate) ClearStyleCode() *ProductUpdate {
	_u.mutation.ClearStyleCode()
	return _u
}

// SetCrawledAt sets the "crawled_at" field.
func (_u *ProductUpdate) SetCrawledAt(v time.Time) *ProductUpdate {
	_u.mutation.SetCrawledAt(v)
	return _u
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableCrawledAt(v *time.Time) *ProductUpdate {
	if v != nil {
		_u.SetCrawledAt(*v)
	}
	return _u
}

// ClearCrawledAt clears the value of the "crawled_at" field.
func (_u *ProductUpdate) ClearCrawledAt() *ProductUpdate {
	_u.mutation.ClearCrawledAt()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ProductUpdate) SetEmbedding(v []float32) *ProductUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *ProductUpdate) AppendEmbedding(v []float32) *ProductUpdate {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ProductUpdate) ClearEmbedding() *ProductUpdate {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetSearchKeywords sets the "search_keywords" field.
func (_u *ProductUpdate) SetSearchKeywords(v []string) *ProductUpdate {
	_u.mutation.SetSearchKeywords(v)
	return _u
}

// AppendSearchKeywords appends value to the "search_keywords" field.
func (_u *ProductUpdate) AppendSearchKeywords(v []string) *ProductUpdate {
	_u.mutation.AppendSearchKeywords(v)
	return _u
}

// ClearSearchKeywords clears the value of the "search_keywords" field.
func (_u *ProductUpdate) ClearSearchKeywords() *ProductUpdate {
	_u.mutation.ClearSearchKeywords()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ProductUpdate) SetFeatured(v bool) *ProductUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableFeatured(v *bool) *ProductUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *ProductUpdate) SetViewCount(v int) *ProductUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableViewCount(v *int) *ProductUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *ProductUpdate) AddViewCount(v int) *ProductUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *ProductUpdate) SetClickCount(v int) *ProductUpdate {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableClickCount(v *int) *ProductUpdate {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *ProductUpdate) AddClickCount(v int) *ProductUpdate {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetPriceNumeric sets the "price_numeric" field.
func (_u *ProductUpdate) SetPriceNumeric(v int) *ProductUpdate {
	_u.mutation.ResetPriceNumeric()
	_u.mutation.SetPriceNumeric(v)
	return _u
}

// SetNillablePriceNumeric sets the "price_numeric" field if the given value is not nil.
func (_u *ProductUpdate) SetNillablePriceNumeric(v *int) *ProductUpdate {
	if v != nil {
		_u.SetPriceNumeric(*v)
	}
	return _u
}

// AddPriceNumeric adds value to the "price_numeric" field.
func (_u *ProductUpdate) AddPriceNumeric(v int) *ProductUpdate {
	_u.mutation.AddPriceNumeric(v)
	return _u
}

// ClearPriceNumeric clears the value of the "price_numeric" field.
func (_u *ProductUpdate) ClearPriceNumeric() *ProductUpdate {
	_u.mutation.ClearPriceNumeric()
	return _u
}

// SetRatingNumeric sets the "rating_numeric" field.
func (_u *ProductUpdate) SetRatingNumeric(v float64) *ProductUpdate {
	_u.mutation.ResetRatingNumeric()
	_u.mutation.SetRatingNumeric(v)
	return _u
}

// SetNillableRatingNumeric sets the "rating_numeric" field if the given value is not nil.
func (_u *ProductUpdate) SetNillableRatingNumeric(v *float64) *ProductUpdate {
	if v != nil {
		_u.SetRatingNumeric(*v)
	}
	return _u
}

// AddRatingNumeric adds value to the "rating_numeric" field.
func (_u *ProductUpdate) AddRatingNumeric(v float64) *ProductUpdate {
	_u.mutation.AddRatingNumeric(v)
	return _u
}

// ClearRatingNumeric clears the value of the "rating_numeric" field.
func (_u *ProductUpdate) ClearRatingNumeric() *ProductUpdate {
	_u.mutation.ClearRatingNumeric()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdate) Mutation() *ProductMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if product.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized product.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := product.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Brand(); ok {
		if err := product.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Product.brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubCategory(); ok {
		if err := product.SubCategoryValidator(v); err != nil {
			return &ValidationError{Name: "sub_category", err: fmt.Errorf(`ent: validator failed for field "Product.sub_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := product.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Product.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceNumeric(); ok {
		if err := product.PriceNumericValidator(v); err != nil {
			return &ValidationError{Name: "price_numeric", err: fmt.Errorf(`ent: validator failed for field "Product.price_numeric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingNumeric(); ok {
		if err := product.RatingNumericValidator(v); err != nil {
			return &ValidationError{Name: "rating_numeric", err: fmt.Errorf(`ent: validator failed for field "Product.rating_numeric": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(product.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(product.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(product.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ActualPrice(); ok {
		_spec.SetField(product.FieldActualPrice, field.TypeString, value)
	}
	if _u.mutation.ActualPriceCleared() {
		_spec.ClearField(product.FieldActualPrice, field.TypeString)
	}
	if value, ok := _u.mutation.SellingPrice(); ok {
		_spec.SetField(product.FieldSellingPrice, field.TypeString, value)
	}
	if _u.mutation.SellingPriceCleared() {
		_spec.ClearField(product.FieldSellingPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(product.FieldDiscount, field.TypeString, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(product.FieldDiscount, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubCategory(); ok {
		_spec.SetField(product.FieldSubCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutOfStock(); ok {
		_spec.SetField(product.FieldOutOfStock, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Seller(); ok {
		_spec.SetField(product.FieldSeller, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		_spec.ClearField(product.FieldSeller, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(product.FieldAverageRating, field.TypeString, value)
	}
	if _u.mutation.AverageRatingCleared() {
		_spec.ClearField(product.FieldAverageRating, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(product.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProductDetails(); ok {
		_spec.SetField(product.FieldProductDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProductDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldProductDetails, value)
		})
	}
	if _u.mutation.ProductDetailsCleared() {
		_spec.ClearField(product.FieldProductDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(product.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(product.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(product.FieldPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StyleCode(); ok {
		_spec.SetField(product.FieldStyleCode, field.TypeString, value)
	}
	if _u.mutation.StyleCodeCleared() {
		_spec.ClearField(product.FieldStyleCode, field.TypeString)
	}
	if value, ok := _u.mutation.CrawledAt(); ok {
		_spec.SetField(product.FieldCrawledAt, field.TypeTime, value)
	}
	if _u.mutation.CrawledAtCleared() {
		_spec.ClearField(product.FieldCrawledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(product.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(product.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.SearchKeywords(); ok {
		_spec.SetField(product.FieldSearchKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSearchKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldSearchKeywords, value)
		})
	}
	if _u.mutation.SearchKeywordsCleared() {
		_spec.ClearField(product.FieldSearchKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(product.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(product.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(product.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(product.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(product.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceNumeric(); ok {
		_spec.SetField(product.FieldPriceNumeric, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceNumeric(); ok {
		_spec.AddField(product.FieldPriceNumeric, field.TypeInt, value)
	}
	if _u.mutation.PriceNumericCleared() {
		_spec.ClearField(product.FieldPriceNumeric, field.TypeInt)
	}
	if value, ok := _u.mutation.RatingNumeric(); ok {
		_spec.SetField(product.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatingNumeric(); ok {
		_spec.AddField(product.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if _u.mutation.RatingNumericCleared() {
		_spec.ClearField(product.FieldRatingNumeric, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *ProductUpdateOne) SetUpdateTime(v time.Time) *ProductUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetOriginalID sets the "original_id" field.
func (_u *ProductUpdateOne) SetOriginalID(v string) *ProductUpdateOne {
	_u.mutation.SetOriginalID(v)
	return _u
}

// SetNillableOriginalID sets the "original_id" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableOriginalID(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetOriginalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ProductUpdateOne) SetTitle(v string) *ProductUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableTitle(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetBrand sets the "brand" field.
func (_u *ProductUpdateOne) SetBrand(v string) *ProductUpdateOne {
	_u.mutation.SetBrand(v)
	return _u
}

// SetNillableBrand sets the "brand" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableBrand(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetBrand(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProductUpdateOne) SetDescription(v string) *ProductUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableDescription(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ProductUpdateOne) ClearDescription() *ProductUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetActualPrice sets the "actual_price" field.
func (_u *ProductUpdateOne) SetActualPrice(v string) *ProductUpdateOne {
	_u.mutation.SetActualPrice(v)
	return _u
}

// SetNillableActualPrice sets the "actual_price" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableActualPrice(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetActualPrice(*v)
	}
	return _u
}

// ClearActualPrice clears the value of the "actual_price" field.
func (_u *ProductUpdateOne) ClearActualPrice() *ProductUpdateOne {
	_u.mutation.ClearActualPrice()
	return _u
}

// SetSellingPrice sets the "selling_price" field.
func (_u *ProductUpdateOne) SetSellingPrice(v string) *ProductUpdateOne {
	_u.mutation.SetSellingPrice(v)
	return _u
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSellingPrice(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetSellingPrice(*v)
	}
	return _u
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (_u *ProductUpdateOne) ClearSellingPrice() *ProductUpdateOne {
	_u.mutation.ClearSellingPrice()
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *ProductUpdateOne) SetDiscount(v string) *ProductUpdateOne {
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableDiscount(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *ProductUpdateOne) ClearDiscount() *ProductUpdateOne {
	_u.mutation.ClearDiscount()
	return _u
}

// SetCategory sets the "category" field.
func (_u *ProductUpdateOne) SetCategory(v string) *ProductUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCategory(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSubCategory sets the "sub_category" field.
func (_u *ProductUpdateOne) SetSubCategory(v string) *ProductUpdateOne {
	_u.mutation.SetSubCategory(v)
	return _u
}

// SetNillableSubCategory sets the "sub_category" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSubCategory(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetSubCategory(*v)
	}
	return _u
}

// SetOutOfStock sets the "out_of_stock" field.
func (_u *ProductUpdateOne) SetOutOfStock(v bool) *ProductUpdateOne {
	_u.mutation.SetOutOfStock(v)
	return _u
}

// SetNillableOutOfStock sets the "out_of_stock" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableOutOfStock(v *bool) *ProductUpdateOne {
	if v != nil {
		_u.SetOutOfStock(*v)
	}
	return _u
}

// SetSeller sets the "seller" field.
func (_u *ProductUpdateOne) SetSeller(v string) *ProductUpdateOne {
	_u.mutation.SetSeller(v)
	return _u
}

// SetNillableSeller sets the "seller" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableSeller(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetSeller(*v)
	}
	return _u
}

// ClearSeller clears the value of the "seller" field.
func (_u *ProductUpdateOne) ClearSeller() *ProductUpdateOne {
	_u.mutation.ClearSeller()
	return _u
}

// SetAverageRating sets the "average_rating" field.
func (_u *ProductUpdateOne) SetAverageRating(v string) *ProductUpdateOne {
	_u.mutation.SetAverageRating(v)
	return _u
}

// SetNillableAverageRating sets the "average_rating" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableAverageRating(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetAverageRating(*v)
	}
	return _u
}

// ClearAverageRating clears the value of the "average_rating" field.
func (_u *ProductUpdateOne) ClearAverageRating() *ProductUpdateOne {
	_u.mutation.ClearAverageRating()
	return _u
}

// SetImages sets the "images" field.
func (_u *ProductUpdateOne) SetImages(v []string) *ProductUpdateOne {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *ProductUpdateOne) AppendImages(v []string) *ProductUpdateOne {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *ProductUpdateOne) ClearImages() *ProductUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// SetProductDetails sets the "product_details" field.
func (_u *ProductUpdateOne) SetProductDetails(v []map[string]string) *ProductUpdateOne {
	_u.mutation.SetProductDetails(v)
	return _u
}

// AppendProductDetails appends value to the "product_details" field.
func (_u *ProductUpdateOne) AppendProductDetails(v []map[string]string) *ProductUpdateOne {
	_u.mutation.AppendProductDetails(v)
	return _u
}

// ClearProductDetails clears the value of the "product_details" field.
func (_u *ProductUpdateOne) ClearProductDetails() *ProductUpdateOne {
	_u.mutation.ClearProductDetails()
	return _u
}

// SetURL sets the "url" field.
func (_u *ProductUpdateOne) SetURL(v string) *ProductUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableURL(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *ProductUpdateOne) ClearURL() *ProductUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetPid sets the "pid" field.
func (_u *ProductUpdateOne) SetPid(v string) *ProductUpdateOne {
	_u.mutation.SetPid(v)
	return _u
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillablePid(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetPid(*v)
	}
	return _u
}

// SetStyleCode sets the "style_code" field.
func (_u *ProductUpdateOne) SetStyleCode(v string) *ProductUpdateOne {
	_u.mutation.SetStyleCode(v)
	return _u
}

// SetNillableStyleCode sets the "style_code" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableStyleCode(v *string) *ProductUpdateOne {
	if v != nil {
		_u.SetStyleCode(*v)
	}
	return _u
}

// ClearStyleCode clears the value of the "style_code" field.
func (_u *ProductUpdateOne) ClearStyleCode() *ProductUpdateOne {
	_u.mutation.ClearStyleCode()
	return _u
}

// SetCrawledAt sets the "crawled_at" field.
func (_u *ProductUpdateOne) SetCrawledAt(v time.Time) *ProductUpdateOne {
	_u.mutation.SetCrawledAt(v)
	return _u
}

// SetNillableCrawledAt sets the "crawled_at" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableCrawledAt(v *time.Time) *ProductUpdateOne {
	if v != nil {
		_u.SetCrawledAt(*v)
	}
	return _u
}

// ClearCrawledAt clears the value of the "crawled_at" field.
func (_u *ProductUpdateOne) ClearCrawledAt() *ProductUpdateOne {
	_u.mutation.ClearCrawledAt()
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *ProductUpdateOne) SetEmbedding(v []float32) *ProductUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// AppendEmbedding appends value to the "embedding" field.
func (_u *ProductUpdateOne) AppendEmbedding(v []float32) *ProductUpdateOne {
	_u.mutation.AppendEmbedding(v)
	return _u
}

// ClearEmbedding clears the value of the "embedding" field.
func (_u *ProductUpdateOne) ClearEmbedding() *ProductUpdateOne {
	_u.mutation.ClearEmbedding()
	return _u
}

// SetSearchKeywords sets the "search_keywords" field.
func (_u *ProductUpdateOne) SetSearchKeywords(v []string) *ProductUpdateOne {
	_u.mutation.SetSearchKeywords(v)
	return _u
}

// AppendSearchKeywords appends value to the "search_keywords" field.
func (_u *ProductUpdateOne) AppendSearchKeywords(v []string) *ProductUpdateOne {
	_u.mutation.AppendSearchKeywords(v)
	return _u
}

// ClearSearchKeywords clears the value of the "search_keywords" field.
func (_u *ProductUpdateOne) ClearSearchKeywords() *ProductUpdateOne {
	_u.mutation.ClearSearchKeywords()
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ProductUpdateOne) SetFeatured(v bool) *ProductUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableFeatured(v *bool) *ProductUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *ProductUpdateOne) SetViewCount(v int) *ProductUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableViewCount(v *int) *ProductUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *ProductUpdateOne) AddViewCount(v int) *ProductUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetClickCount sets the "click_count" field.
func (_u *ProductUpdateOne) SetClickCount(v int) *ProductUpdateOne {
	_u.mutation.ResetClickCount()
	_u.mutation.SetClickCount(v)
	return _u
}

// SetNillableClickCount sets the "click_count" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableClickCount(v *int) *ProductUpdateOne {
	if v != nil {
		_u.SetClickCount(*v)
	}
	return _u
}

// AddClickCount adds value to the "click_count" field.
func (_u *ProductUpdateOne) AddClickCount(v int) *ProductUpdateOne {
	_u.mutation.AddClickCount(v)
	return _u
}

// SetPriceNumeric sets the "price_numeric" field.
func (_u *ProductUpdateOne) SetPriceNumeric(v int) *ProductUpdateOne {
	_u.mutation.ResetPriceNumeric()
	_u.mutation.SetPriceNumeric(v)
	return _u
}

// SetNillablePriceNumeric sets the "price_numeric" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillablePriceNumeric(v *int) *ProductUpdateOne {
	if v != nil {
		_u.SetPriceNumeric(*v)
	}
	return _u
}

// AddPriceNumeric adds value to the "price_numeric" field.
func (_u *ProductUpdateOne) AddPriceNumeric(v int) *ProductUpdateOne {
	_u.mutation.AddPriceNumeric(v)
	return _u
}

// ClearPriceNumeric clears the value of the "price_numeric" field.
func (_u *ProductUpdateOne) ClearPriceNumeric() *ProductUpdateOne {
	_u.mutation.ClearPriceNumeric()
	return _u
}

// SetRatingNumeric sets the "rating_numeric" field.
func (_u *ProductUpdateOne) SetRatingNumeric(v float64) *ProductUpdateOne {
	_u.mutation.ResetRatingNumeric()
	_u.mutation.SetRatingNumeric(v)
	return _u
}

// SetNillableRatingNumeric sets the "rating_numeric" field if the given value is not nil.
func (_u *ProductUpdateOne) SetNillableRatingNumeric(v *float64) *ProductUpdateOne {
	if v != nil {
		_u.SetRatingNumeric(*v)
	}
	return _u
}

// AddRatingNumeric adds value to the "rating_numeric" field.
func (_u *ProductUpdateOne) AddRatingNumeric(v float64) *ProductUpdateOne {
	_u.mutation.AddRatingNumeric(v)
	return _u
}

// ClearRatingNumeric clears the value of the "rating_numeric" field.
func (_u *ProductUpdateOne) ClearRatingNumeric() *ProductUpdateOne {
	_u.mutation.ClearRatingNumeric()
	return _u
}

// Mutation returns the ProductMutation object of the builder.
func (_u *ProductUpdateOne) Mutation() *ProductMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (_u *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Product entity.
func (_u *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if product.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized product.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := product.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := product.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Product.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Brand(); ok {
		if err := product.BrandValidator(v); err != nil {
			return &ValidationError{Name: "brand", err: fmt.Errorf(`ent: validator failed for field "Product.brand": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := product.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "Product.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SubCategory(); ok {
		if err := product.SubCategoryValidator(v); err != nil {
			return &ValidationError{Name: "sub_category", err: fmt.Errorf(`ent: validator failed for field "Product.sub_category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := product.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Product.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceNumeric(); ok {
		if err := product.PriceNumericValidator(v); err != nil {
			return &ValidationError{Name: "price_numeric", err: fmt.Errorf(`ent: validator failed for field "Product.price_numeric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RatingNumeric(); ok {
		if err := product.RatingNumericValidator(v); err != nil {
			return &ValidationError{Name: "rating_numeric", err: fmt.Errorf(`ent: validator failed for field "Product.rating_numeric": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(product.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OriginalID(); ok {
		_spec.SetField(product.FieldOriginalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(product.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Brand(); ok {
		_spec.SetField(product.FieldBrand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(product.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ActualPrice(); ok {
		_spec.SetField(product.FieldActualPrice, field.TypeString, value)
	}
	if _u.mutation.ActualPriceCleared() {
		_spec.ClearField(product.FieldActualPrice, field.TypeString)
	}
	if value, ok := _u.mutation.SellingPrice(); ok {
		_spec.SetField(product.FieldSellingPrice, field.TypeString, value)
	}
	if _u.mutation.SellingPriceCleared() {
		_spec.ClearField(product.FieldSellingPrice, field.TypeString)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(product.FieldDiscount, field.TypeString, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(product.FieldDiscount, field.TypeString)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(product.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.SubCategory(); ok {
		_spec.SetField(product.FieldSubCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutOfStock(); ok {
		_spec.SetField(product.FieldOutOfStock, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Seller(); ok {
		_spec.SetField(product.FieldSeller, field.TypeString, value)
	}
	if _u.mutation.SellerCleared() {
		_spec.ClearField(product.FieldSeller, field.TypeString)
	}
	if value, ok := _u.mutation.AverageRating(); ok {
		_spec.SetField(product.FieldAverageRating, field.TypeString, value)
	}
	if _u.mutation.AverageRatingCleared() {
		_spec.ClearField(product.FieldAverageRating, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(product.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(product.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProductDetails(); ok {
		_spec.SetField(product.FieldProductDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedProductDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldProductDetails, value)
		})
	}
	if _u.mutation.ProductDetailsCleared() {
		_spec.ClearField(product.FieldProductDetails, field.TypeJSON)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(product.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(product.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Pid(); ok {
		_spec.SetField(product.FieldPid, field.TypeString, value)
	}
	if value, ok := _u.mutation.StyleCode(); ok {
		_spec.SetField(product.FieldStyleCode, field.TypeString, value)
	}
	if _u.mutation.StyleCodeCleared() {
		_spec.ClearField(product.FieldStyleCode, field.TypeString)
	}
	if value, ok := _u.mutation.CrawledAt(); ok {
		_spec.SetField(product.FieldCrawledAt, field.TypeTime, value)
	}
	if _u.mutation.CrawledAtCleared() {
		_spec.ClearField(product.FieldCrawledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(product.FieldEmbedding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEmbedding(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldEmbedding, value)
		})
	}
	if _u.mutation.EmbeddingCleared() {
		_spec.ClearField(product.FieldEmbedding, field.TypeJSON)
	}
	if value, ok := _u.mutation.SearchKeywords(); ok {
		_spec.SetField(product.FieldSearchKeywords, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSearchKeywords(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, product.FieldSearchKeywords, value)
		})
	}
	if _u.mutation.SearchKeywordsCleared() {
		_spec.ClearField(product.FieldSearchKeywords, field.TypeJSON)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(product.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(product.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(product.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClickCount(); ok {
		_spec.SetField(product.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedClickCount(); ok {
		_spec.AddField(product.FieldClickCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PriceNumeric(); ok {
		_spec.SetField(product.FieldPriceNumeric, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriceNumeric(); ok {
		_spec.AddField(product.FieldPriceNumeric, field.TypeInt, value)
	}
	if _u.mutation.PriceNumericCleared() {
		_spec.ClearField(product.FieldPriceNumeric, field.TypeInt)
	}
	if value, ok := _u.mutation.RatingNumeric(); ok {
		_spec.SetField(product.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRatingNumeric(); ok {
		_spec.AddField(product.FieldRatingNumeric, field.TypeFloat64, value)
	}
	if _u.mutation.RatingNumericCleared() {
		_spec.ClearField(product.FieldRatingNumeric, field.TypeFloat64)
	}
	_node = &Product{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
