// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/payment/v1/payment.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod int32

const (
	PaymentMethod_OVO         PaymentMethod = 0
	PaymentMethod_DANA        PaymentMethod = 1
	PaymentMethod_GOPAY       PaymentMethod = 2
	PaymentMethod_SHOPEEPAY   PaymentMethod = 3
	PaymentMethod_BCA         PaymentMethod = 4
	PaymentMethod_BRI         PaymentMethod = 5
	PaymentMethod_MANDIRI     PaymentMethod = 6
	PaymentMethod_BNI         PaymentMethod = 7
	PaymentMethod_MASTERCARD  PaymentMethod = 8
	PaymentMethod_VISA        PaymentMethod = 9
	PaymentMethod_KREDIVO     PaymentMethod = 10
	PaymentMethod_GOPAY_LATER PaymentMethod = 11
	PaymentMethod_UNSPECIFIED PaymentMethod = 12
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0:  "OVO",
		1:  "DANA",
		2:  "GOPAY",
		3:  "SHOPEEPAY",
		4:  "BCA",
		5:  "BRI",
		6:  "MANDIRI",
		7:  "BNI",
		8:  "MASTERCARD",
		9:  "VISA",
		10: "KREDIVO",
		11: "GOPAY_LATER",
		12: "UNSPECIFIED",
	}
	PaymentMethod_value = map[string]int32{
		"OVO":         0,
		"DANA":        1,
		"GOPAY":       2,
		"SHOPEEPAY":   3,
		"BCA":         4,
		"BRI":         5,
		"MANDIRI":     6,
		"BNI":         7,
		"MASTERCARD":  8,
		"VISA":        9,
		"KREDIVO":     10,
		"GOPAY_LATER": 11,
		"UNSPECIFIED": 12,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_api_payment_v1_payment_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

type PayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        PaymentMethod          `protobuf:"varint,1,opt,name=method,proto3,enum=api.payment.v1.PaymentMethod" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PayRequest) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_OVO
}

type PayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayReply) Reset() {
	*x = PayReply{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReply) ProtoMessage() {}

func (x *PayReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReply.ProtoReflect.Descriptor instead.
func (*PayReply) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PayReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PayReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\x0eapi.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"C\n" +
	"\n" +
	"PayRequest\x125\n" +
	"\x06method\x18\x01 \x01(\x0e2\x1d.api.payment.v1.PaymentMethodR\x06method\"<\n" +
	"\bPayReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status*\xad\x01\n" +
	"\rPaymentMethod\x12\a\n" +
	"\x03OVO\x10\x00\x12\b\n" +
	"\x04DANA\x10\x01\x12\t\n" +
	"\x05GOPAY\x10\x02\x12\r\n" +
	"\tSHOPEEPAY\x10\x03\x12\a\n" +
	"\x03BCA\x10\x04\x12\a\n" +
	"\x03BRI\x10\x05\x12\v\n" +
	"\aMANDIRI\x10\x06\x12\a\n" +
	"\x03BNI\x10\a\x12\x0e\n" +
	"\n" +
	"MASTERCARD\x10\b\x12\b\n" +
	"\x04VISA\x10\t\x12\v\n" +
	"\aKREDIVO\x10\n" +
	"\x12\x0f\n" +
	"\vGOPAY_LATER\x10\v\x12\x0f\n" +
	"\vUNSPECIFIED\x10\f2Z\n" +
	"\aPayment\x12O\n" +
	"\x03Pay\x12\x1a.api.payment.v1.PayRequest\x1a\x18.api.payment.v1.PayReply\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/payB3\n" +
	"\x0eapi.payment.v1P\x01Z\x1fyinni_backend/api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(PaymentMethod)(0), // 0: api.payment.v1.PaymentMethod
	(*PayRequest)(nil), // 1: api.payment.v1.PayRequest
	(*PayReply)(nil),   // 2: api.payment.v1.PayReply
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: api.payment.v1.PayRequest.method:type_name -> api.payment.v1.PaymentMethod
	1, // 1: api.payment.v1.Payment.Pay:input_type -> api.payment.v1.PayRequest
	2, // 2: api.payment.v1.Payment.Pay:output_type -> api.payment.v1.PayReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		EnumInfos:         file_api_payment_v1_payment_proto_enumTypes,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
